name: '1. Quick Feedback'

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize

concurrency:
  group: Branch-Environment-${{ github.head_ref }}
  cancel-in-progress: true

jobs:

  sanity:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup-scala
        uses: olafurpg/setup-scala@v13
        with:
          java-version: temurin@17.0.5=tgz+https://github.com/adoptium/temurin17-binaries/releases/download/jdk-17.0.5%2B8/OpenJDK17U-jdk_x64_linux_hotspot_17.0.5_8.tar.gz
      - name: Run sanity
        run: "sbt sanity"
