name: '2. Full Feedback'

on:
  workflow_dispatch:
  workflow_call:
  push:
    branches: [ develop ]

concurrency:
  group: Branch-Environment-${{ github.ref_name }}
  cancel-in-progress: false

jobs:
  commit-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: commit-distance
        run: |
          git checkout main
          dist=$(git log --oneline develop ^main | wc -l)
          echo "COMMIT_DISTANCE=$dist" >> $GITHUB_ENV
      - uses: actions/checkout@v3
        with:
          fetch-depth: ${{ env.COMMIT_DISTANCE }}
      - uses: wagoid/commitlint-github-action@v5
        with:
          failOnWarnings: true
          firstParent: false

  sanity:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup-scala
        uses: olafurpg/setup-scala@v13
        with:
          java-version: temurin@17.0.5=tgz+https://github.com/adoptium/temurin17-binaries/releases/download/jdk-17.0.5%2B8/OpenJDK17U-jdk_x64_linux_hotspot_17.0.5_8.tar.gz
      - name: Run sanity
        run: "sbt sanity"

  has-release:
    needs: [ commit-lint, sanity ]
    uses: ./.github/workflows/semantic_release.yml
    with:
      dry_run: true
      branch: develop

  publish-snapshot:
    needs: [ has-release ]
    if: ${{ needs.has-release.outputs.published }} == 'true'
    uses: ./.github/workflows/publish.yml
    with:
      isSnapshot: true
    secrets: inherit

  push-to-main:
    runs-on: ubuntu-latest
    needs: [ commit-lint, sanity ]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: push develop to main
        run: |
          git push origin develop:main

  reset-to-main:
    runs-on: ubuntu-latest
    needs: [ commit-lint, sanity ]
    if: ${{ always() && contains(needs.*.result, 'failure') }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: reset develop to main
        run: |
          git checkout main
          git branch -D develop
          git checkout -b develop
          git push -f origin develop
