name: '2. Full Feedback'

on:
  workflow_dispatch:
  push:
    branches: [ develop ]

concurrency:
  group: Branch-Environment-${{ github.ref_name }}
  cancel-in-progress: false

jobs:
  commit-lint:
    uses: ./.github/workflows/commit_lint.yml

  sanity:
    uses: ./.github/workflows/sanity.yml

  has-release:
    needs: [ commit-lint, sanity ]
    uses: ./.github/workflows/semantic_release.yml
    with:
      dry_run: true
      branch: develop

  publish-snapshot:
    needs: [ has-release ]
    if: ${{ needs.has-release.outputs.published }} == 'true'
    uses: ./.github/workflows/publish.yml
    with:
      isSnapshot: true
    secrets: inherit

  push-to-main:
    runs-on: ubuntu-latest
    needs: [ commit-lint, sanity ]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: push develop to main
        run: |
          git push origin develop:main

  reset-to-main:
    runs-on: ubuntu-latest
    needs: [ commit-lint, sanity ]
    if: ${{ always() && contains(needs.*.result, 'failure') }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: reset develop to main
        run: |
          git checkout main
          git branch -D develop
          git checkout -b develop
          git push -f origin develop
