name: '3. Release'

on:
  workflow_dispatch:

jobs:
  release:
    uses: ./.github/workflows/semantic_release.yml
    with:
      dry_run: false
      branch: main

  publish:
    needs: release
    if: ${{ needs.create_release.outputs.published }} == 'true'
    uses: ./.github/workflows/publish.yml
    with:
      isSnapshot: false
    secrets: inherit
